environment:
  RTOOLS_ARCH: x86_64
  PfxUri:
    secure: z+vP1iY4odY07BV7v+yfuA2MBKQFFLGokZoefPhz22evsMT/KnwtB4NgcYNLJheI
  CertPassword:
    secure: nwSwtaLCl6Xo5sfqKLvO30aFFGCgjGJ2GKTqS33zkJg=
  SignTool: C:\Program Files (x86)\Windows Kits\8.1\bin\x64\signtool.exe
  CertKit: C:\Program Files (x86)\Windows Kits\10\App Certification Kit\appcert.exe
  KeyFile: C:\jeroen.pfx

install:
    - ps: Import-Module .\scripts.ps1
    - ps: InstallInno
    - ps: InstallMiktex
    - ps: InstallRtoolsExe
    - ps: SetTimezone

build_script:
  - C:\rtools40\usr\bin\bash --login -c "$(cygpath ${APPVEYOR_BUILD_FOLDER})/build.sh"

after_build:
  - move src\build64\src\gnuwin32\installer\R-testing-win.exe .
  - ps: Start-FileDownload $env:PfxUri -FileName $env:KeyFile
  - ps: SignFiles R-testing-win.exe
  - ps: Remove-Item –path $env:KeyFile

artifacts:
  - path: R-testing-win.exe
    name: installer

on_finish:
  - 7z a r-devel.zip *.log
  - appveyor PushArtifact r-devel.zip

deploy:
  - provider: BinTray
    username: jeroen
    subject: rtools
    repo: installer
    package: testing
    version: latest
    publish: true
    override: true
    api_key:
      secure: rKoNWcAgUrOM7QLX4cEvA1iKoY2DR4ps/1PRveq7rJknjQjcpKx8xGs42CJPhDwJ
    on:
      branch: master
