environment:
  RTOOLS_ARCH: x86_64
  PfxUri:
    secure: z+vP1iY4odY07BV7v+yfuA2MBKQFFLGokZoefPhz22evsMT/KnwtB4NgcYNLJheI
  CertPassword:
    secure: nwSwtaLCl6Xo5sfqKLvO30aFFGCgjGJ2GKTqS33zkJg=
  SignTool: C:\Program Files (x86)\Windows Kits\8.1\bin\x64\signtool.exe
  CertKit: C:\Program Files (x86)\Windows Kits\10\App Certification Kit\appcert.exe
  KeyFile: C:\jeroen.pfx
  matrix:
  - version: r-testing
  - version: r-devel

install:
    - ps: Import-Module .\scripts.ps1
    - ps: InstallInno
    - ps: InstallMiktex
    - ps: InstallRtoolsExe
    - ps: SetTimezone

build_script:
  - C:\rtools40\usr\bin\bash --login -c "$(cygpath ${APPVEYOR_BUILD_FOLDER})/build-installer.sh"

after_build:
  - move "src\build64\src\gnuwin32\installer\%version%-win.exe" .
  - ps: Start-FileDownload $env:PfxUri -FileName $env:KeyFile
  - ps: SignFiles R-testing-win.exe
  - ps: Remove-Item –path $env:KeyFile

artifacts:
  - path: "%version%-win.exe"
    name: installer
  - path: r-devel.log
    name: buildlog

on_finish:
  - 7z a buildlog.zip *.log
  - appveyor PushArtifact buildlog.zip

on_failure:
  - 7z a tests.zip src\build64\tests\*.Rout*
  - appveyor PushArtifact tests.zip

deploy:
  - provider: BinTray
    username: jeroen
    subject: rtools
    repo: installer
    package: testing
    version: latest
    publish: true
    override: true
    api_key:
      secure: rKoNWcAgUrOM7QLX4cEvA1iKoY2DR4ps/1PRveq7rJknjQjcpKx8xGs42CJPhDwJ
    on:
      branch: master
      version: r-testing
