
# # collect IP and username for rdp
# init:
#  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

version: 0.1.0-{build}-{branch}

# Do not build on tags (GitHub and BitBucket)
skip_tags: true

# Start builds on tags only (GitHub and BitBucket)
# skip_non_tags: true

branches:
  only:
    - master

environment:
  RTOOLS_ARCH: x86_64
# PfxUri:
#   secure: z+vP1iY4odY07BV7v+yfuA2MBKQFFLGokZoefPhz22ewYZAm6XZ8jsdphTFYkn7L
# CertPassword:
#   secure: nwSwtaLCl6Xo5sfqKLvO30aFFGCgjGJ2GKTqS33zkJg=
# SignTool: C:\Program Files (x86)\Windows Kits\8.1\bin\x64\signtool.exe
# CertKit: C:\Program Files (x86)\Windows Kits\10\App Certification Kit\appcert.exe
# KeyFile: C:\jeroen.pfx
  matrix:
#     - rsource_url: https://cran.r-project.org/src/base-prerelease/R-latest.tar.gz
#       rversion: r-patched
#       cran: true
#       BUILDFLAGS: 'DEBUG=T USE_ATLAS=YES ATLAS_PATH=/mingw$(WIN)/lib/'
#       MARCHMTUNE: '-march=corei7 -mavx -mavx2     -funroll-loops -ffast-math'
#       MARCHMTUNENAME: 'CPU Build CoreI7 with AVX2'
#       DIST_BUILD: 'with Debugging Symbols'
#       DEPLOYNAME: Generic_Debug_Optimize_Test

  - rsource_url: https://cran.r-project.org/src/base-prerelease/R-latest.tar.gz
    rversion: r-patched
    cran: true
    BUILDFLAGS: DEBUG=T
    MARCHMTUNE:
    MARCHMTUNENAME: 'CPU Build Generic'
    DIST_BUILD: 'with Debugging Symbols'
    DEPLOYNAME: Generic_Debug

  # in this form (did not successfully build(requested stronger debugging -> ALTREP error?))
  # so tried a 2nd time
  # 
  - rsource_url: https://cran.r-project.org/src/base/R-4/R-4.1.0.tar.gz
    rversion: r-release
    cran: true
    BUILDFLAGS: DEBUG=T
    MARCHMTUNE:
    MARCHMTUNENAME: 'CPU Build Generic'
    DIST_BUILD: 'with Debugging Symbols'
    DEPLOYNAME: Generic_Debug

#     - rsource_url: https://cran.r-project.org/src/base-prerelease/R-latest.tar.gz
#       rversion: r-patched
#       cran: true
#       BUILDFLAGS: 'USE_ATLAS=YES ATLAS_PATH=/mingw$(WIN)/lib/'
#       MARCHMTUNE: '-march=corei7 -mavx -mavx2 -O3 -funroll-loops -ffast-math'
#       MARCHMTUNENAME: 'CPU Build CoreI7 with AVX2'
#       DIST_BUILD: 'without Debugging Symbols'
#       DEPLOYNAME: CoreI7_mAVX2_NoDebug
#       
#     - rsource_url: https://cran.r-project.org/src/base-prerelease/R-latest.tar.gz
#       rversion: r-patched
#       cran: true
#       BUILDFLAGS: DEBUG=T
#       MARCHMTUNE:
#       MARCHMTUNENAME: 'CPU Build Generic'
#       DIST_BUILD: 'with Debugging Symbols'
#       DEPLOYNAME: Generic_Debug
#     - rsource_url: https://cran.r-project.org/src/base-prerelease/R-devel.tar.gz
#       rversion: r-devel
#       cran: true
#       BUILDFLAGS: 'USE_ATLAS=YES ATLAS_PATH=/mingw$(WIN)/lib/'
#       MARCHMTUNE: '-march=corei7 -mavx -mavx2 -O3 -funroll-loops -ffast-math'
#       MARCHMTUNENAME: 'CPU Build CoreI7 with AVX2'
#       DIST_BUILD: 'without Debugging Symbols'
#       DEPLOYNAME: CoreI7_mAVX2_NoDebug
#     - rsource_url: https://cran.r-project.org/src/base-prerelease/R-devel.tar.gz
#       rversion: r-devel
#       cran: true
#       BUILDFLAGS: DEBUG=T
#       MARCHMTUNE:
#       MARCHMTUNENAME: 'CPU Build Generic'
#       DIST_BUILD: 'with Debugging Symbols'
#       DEPLOYNAME: Generic_Debug

install:
    - ps: Import-Module .\scripts.ps1
    - ps: InstallInno
    - ps: InstallMiktex
    - ps: InstallRtoolsExe
    - ps: SetTimezone

build_script:
  - C:\rtools40\usr\bin\bash --login -c "$(cygpath ${APPVEYOR_BUILD_FOLDER})/full-build.sh"

after_build:
  - cd pkg\r-installer
  - call target.cmd
  - move ..\..\src\R-source\src\gnuwin32\installer\%target%-win.exe .
# - ps: Start-FileDownload $env:PfxUri -FileName $env:KeyFile
# - ps: SignFiles "${env:target}-win.exe"
# - ps: Remove-Item –path $env:KeyFile
  - md5sum %target%-win.exe > md5sum.txt.%target%
# - 7z a -t7z -mmt24 -mx7 ..\..\%target%-win.7z %target%-win.exe md5sum.txt.%target% *.log *.html SVN-REVISION.* README.*
  - 7z a -t7z -mmt24 -mx7 ..\..\%APPVEYOR_PROJECT_SLUG%_%appveyor_build_version%_%rversion%_%target%_%revision%_%DEPLOYNAME%.7z %target%-win.exe md5sum.txt.%target% *.log *.html SVN-REVISION.* README.*
# - move %target%-win.exe ..\..\
  - cd ..\..

artifacts:
  - path: "%APPVEYOR_PROJECT_SLUG%_%appveyor_build_version%_%rversion%_%target%_%revision%_%DEPLOYNAME%.7z"
    name: "%APPVEYOR_PROJECT_SLUG%_%appveyor_build_version%_%rversion%_%target%_%revision%_%DEPLOYNAME%.7z"

on_failure:
  - echo Total build time (with tests) takes OVER one hour
  - echo so build+tests is not done (only "build" is done.)
  - echo Test result are obtained from . . .
  - echo
  - echo https://ftp.opencpu.org/current/check.log
  - echo https://ftp.opencpu.org/archive/r-patched/svn_number/check.log
  - echo https://ftp.opencpu.org/archive/r-release/R-x.y.z/check.log

deploy:
  release: "%APPVEYOR_PROJECT_SLUG%_%appveyor_build_version%_%rversion%_%target%_%revision%_%DEPLOYNAME%.7z"
  provider: GitHub
  auth_token:
    secure: KzS1DumC2yBg2LGN9x3AemHFOjAdp+rD58rW5aGGpwW4Pfdwdm7AmRpYKprPY8Gs
  artifact: "%APPVEYOR_PROJECT_SLUG%_%appveyor_build_version%_%rversion%_%target%_%revision%_%DEPLOYNAME%.7z"
  draft: false
  prerelease: false
  on:
    branch: master

on_finish:
  - echo target %target%
  - echo revision %revision%
  - echo DEPLOYNAME %DEPLOYNAME%
  #
  # these dissapear after 7 days
  - dir R-latest.tar.gz 2>nul
  - appveyor PushArtifact R-latest.tar.gz
  - dir R-devel.tar.gz  2>nul
  - appveyor PushArtifact R-devel.tar.gz
  - cp R-latest.tar.gz    R-latest_%target%_%revision%_%DEPLOYNAME%.tar.gz 2>nul
  - appveyor PushArtifact R-latest_%target%_%revision%_%DEPLOYNAME%.tar.gz
  - cp R-devel.tar.gz     R-devel_%target%_%revision%_%DEPLOYNAME%.tar.gz 2>nul
  - appveyor PushArtifact R-devel_%target%_%revision%_%DEPLOYNAME%.tar.gz
  - dir %target%.tar.gz 2>nul
  - cp  %target%.tar.gz %target%_%revision%_%DEPLOYNAME%.tar.gz 2>nul
  - appveyor PushArtifact %target%.tar.gz
  - appveyor PushArtifact %target%_%revision%_%DEPLOYNAME%.tar.gz
#
#   - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
# # remove locking file from the desktop
